version: "3.8"

services:
  client:
    build:
      context: ./Vprofile
    ports:
      - "8081:8080"
    container_name: Vprofile
    depends_on:
      - Webapp

  api:
    build:
      context: ./Webapp
    ports:
      - "8082:8080"
    restart: always
    container_name: Webapp-1
    depends_on:
